name: Run Levanter Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: |
          uv pip install pytest ruff
          uv pip install "jax[cpu]==0.5.3" "jaxlib[cpu]==0.5.3" .[dev]

      - name: Install Levanter from source
        run: |
          cd ..
          git clone https://github.com/stanford-crfm/levanter.git
          cd levanter
          uv pip install -e .[tests]
          uv pip install -r tests/requirements.txt
          # i don't know why this is necessary
          uv pip install tensorboardX
      - name: Install Haliax on top
        run: |
          # install second since levanter will install a built version of haliax
          cd ../haliax
      - name: Test levanter with pytest
        run: |
          cd ../levanter
          XLA_FLAGS=--xla_force_host_platform_device_count=8 PYTHONPATH=tests:src:../src pytest tests -m "not entry and not slow"
